### ISSUE TITLE
'never-add in headers causes errors

### ISSUE THREAD

**Issue by erikuhlmann** [rmculpepper/racket-http123#3]
currently http123 is failing on some HTTP/2 endpoints seemingly due to HPACK usage and the resulting 'never-add keyword in header entries -- this causes some processing in h2-client-app.rkt to start failing as it expects header entries are `(list name value)`

I don't have a full minimal reproducible example yet (it looks like it depends on specific server behavior) but here's an example of an error received (triggered at https://github.com/rmculpepper/racket-http123/blob/2aecd4e7b487c29239b4f93fdd7f474429192057/http123-lib/private/h2-client-app.rkt#L289 due to `:status` being missed in `split-pseudo-header` because `:status` was of the form `(#":status" #"200" never-add)`)

```
exn:fail: sync-request: bad or missing status from server                                        
   code: 'bad-status                                                                                       
   request: GET https://<...>/...                                                                   
   received: 'yes                                                                                          
   version: 'http/2   
```

the code looked like

```
  (define client (http-client))
  (define req (request 'GET *url*))
  (define res (send client sync-request req))
```

**Comment by rmculpepper** [comment]
Thanks for the report! I've pushed a fix and a test.
